### ISSUE TITLE
REPORTE PROYECTO FINAL 

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/proyecto-final-equipo-fgr#2]
Reporte del Proyecto Final - Sprint 4

[Sprint4 - ProyectoFinal.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo-fgr/files/6773201/Sprint4.-.ProyectoFinal.pdf)

**Comment by uzias10** [comment]
Buen trabajo, cumple con los requisitos de la rubrica.
Cal: 80/80.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
